### ISSUE TITLE
`UnsafeLegacyRenegotiation` option not being inherited

### ISSUE THREAD

**Issue by cicdguy** [jeroen/curl#304]
We have a VPN that prohibits unsafe policy renegotiation, which we bypass by setting the following in the system-wide OpenSSL configuration:

```ini
$ tail -3 /etc/ssl/openssl.cnf

[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=2
Options = UnsafeLegacyRenegotiation
```

This helps us make a request to https://rest.ensembl.org

```yaml
$ curl -I "https://rest.ensembl.org"

HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 0
Vary: Accept-Encoding,User-Agent
X-Runtime: 0.007272
X-RateLimit-Limit: 55000
X-RateLimit-Reset: 1640
X-RateLimit-Period: 3600
X-RateLimit-Remaining: 54998
Vary: Origin
Date: Mon, 10 Jul 2023 13:32:40 GMT
```

If the `UnsafeLegacyRenegotiation` option is _not_ set, the result looks like this:

```
curl: (35) error:0A000152:SSL routines::unsafe legacy renegotiation disabled
```

Now, with the `curl` R package, when we _do_ set the `UnsafeLegacyRenegotiation` option and make a request to https://rest.ensembl.org, we see that the option is not inherited:

```R
> curl::curl_fetch_memory("https://rest.ensembl.org")
Error in curl::curl_fetch_memory("https://rest.ensembl.org") :
  error:0A000152:SSL routines::unsafe legacy renegotiation disabled
Execution halted
```

Needless to say, the above works fine when we're not on a VPN.

#### OS

```env
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

#### R

```$
Using libcurl 7.81.0 with OpenSSL/3.0.2

R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] curl_5.0.1

loaded via a namespace (and not attached):
[1] compiler_4.3.1
```

Any advise on getting `curl` to inherit the option from the config is greatly appreciated. Thanks!
